services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hw4-app:latest
    container_name: hw4_app
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - external
      - internal
    profiles:
      - dev
      - prod
    mem_limit: 512m
    cpus: "0.50"
    deploy:
      resources:
        reservations:
          memory: 256m
          cpus: "0.25"

  db:
    image: postgres:16
    container_name: hw4_db
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - dev
      - prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    mem_limit: 512m
    cpus: "0.50"
    deploy:
      resources:
        reservations:
          memory: 256m
          cpus: "0.25"

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge

volumes:
  postgres_data:
