apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw4-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw4-db
  template:
    metadata:
      labels:
        app: hw4-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: hw4-db-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: hw4-db
spec:
  selector:
    app: hw4-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw4-app
  template:
    metadata:
      labels:
        app: hw4-app
    spec:
      containers:
        - name: hw4-app
          image: ghcr.io/mariyakukhtinova-sys/hw4-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: hw4-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hw4-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hw4-db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: hw4-db
            - name: DB_PORT
              value: "5432"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: hw4-app-service
spec:
  selector:
    app: hw4-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
